//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassXYZ.Vault.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PassXYZ.Vault.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement.
        /// </summary>
        internal static string about_acknowledgement {
            get {
                return ResourceManager.GetString("about_acknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassXYZ.Vault is built on top of KPCLib which is a library changed based on KeePassLib. KPCLib enhanced KeePassLib so that it can be built as a PCL or .netstandard Library to run on .NET MAUI or Xamarin. KeePassLib is part of KeePass project developed by Dominik Reichl. The official website of KeePass is:.
        /// </summary>
        internal static string about_keepass {
            get {
                return ResourceManager.GetString("about_keepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information and source code of KPCLib can be found at:.
        /// </summary>
        internal static string about_kpclib {
            get {
                return ResourceManager.GetString("about_kpclib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        internal static string about_learn_more {
            get {
                return ResourceManager.GetString("about_learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2022, Roger Ye. All rights reserved..
        /// </summary>
        internal static string about_passxyz_copyright {
            get {
                return ResourceManager.GetString("about_passxyz_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassXYZ.Vault is licensed under the GNU General Public License v3.0 . You may not use this file except in compliance with the License. You may obtain a copy of the License at.
        /// </summary>
        internal static string about_passxyz_license {
            get {
                return ResourceManager.GetString("about_passxyz_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This brief introduction is meant for those who are the new users of [PassXYZ](https://passxyz.github.io/). If you are a [KeePass](https://keepass.info/) veteran, you may skip this article and read another one called _In-depth understanding of PassXYZ_ on the [PassXYZ](https://passxyz.github.io/) website which can be found by clicking **Learn More** in menu item **Help**. 
        ///
        ///[PassXYZ](https://passxyz.github.io/) is similar to other password management software. It is quite easy to use. After the installatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_passxyz_usage {
            get {
                return ResourceManager.GetString("about_passxyz_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can submit problem report and get more information on how to use PassXYZ from the website below..
        /// </summary>
        internal static string about_passxyz_web {
            get {
                return ResourceManager.GetString("about_passxyz_web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you encounter any problems when using PassXYZ, please send the problem report to PassXYZ Wechat public account or the email address passxyz@foxmail.com..
        /// </summary>
        internal static string about_problem_report {
            get {
                return ResourceManager.GetString("about_problem_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no problem report found..
        /// </summary>
        internal static string about_problem_report_not_found {
            get {
                return ResourceManager.GetString("about_problem_report_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send problem report.
        /// </summary>
        internal static string about_problem_report_send {
            get {
                return ResourceManager.GetString("about_problem_report_send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal information management system.
        /// </summary>
        internal static string about_slogan {
            get {
                return ResourceManager.GetString("about_slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://passxyz.github.io/categories/Help/.
        /// </summary>
        internal static string about_url {
            get {
                return ResourceManager.GetString("about_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also provide feedback through PassXYZ Wechat public account. PassXYZ Wechat public account is passxyz_kpclib. Or, you may wish to scan the QRcode below..
        /// </summary>
        internal static string about_wechat_info {
            get {
                return ResourceManager.GetString("about_wechat_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string action_id_add {
            get {
                return ResourceManager.GetString("action_id_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add icon.
        /// </summary>
        internal static string action_id_add_icon {
            get {
                return ResourceManager.GetString("action_id_add_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string action_id_attach {
            get {
                return ResourceManager.GetString("action_id_attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string action_id_browse {
            get {
                return ResourceManager.GetString("action_id_browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string action_id_cancel {
            get {
                return ResourceManager.GetString("action_id_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change icon.
        /// </summary>
        internal static string action_id_change_icon {
            get {
                return ResourceManager.GetString("action_id_change_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string action_id_close {
            get {
                return ResourceManager.GetString("action_id_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Config.
        /// </summary>
        internal static string action_id_cloud_config {
            get {
                return ResourceManager.GetString("action_id_cloud_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string action_id_copy {
            get {
                return ResourceManager.GetString("action_id_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string action_id_cut {
            get {
                return ResourceManager.GetString("action_id_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string action_id_delete {
            get {
                return ResourceManager.GetString("action_id_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Sync.
        /// </summary>
        internal static string action_id_disable_sync {
            get {
                return ResourceManager.GetString("action_id_disable_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string action_id_edit {
            get {
                return ResourceManager.GetString("action_id_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sync.
        /// </summary>
        internal static string action_id_enable_sync {
            get {
                return ResourceManager.GetString("action_id_enable_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string action_id_export {
            get {
                return ResourceManager.GetString("action_id_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string action_id_generatebarcode {
            get {
                return ResourceManager.GetString("action_id_generatebarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code.
        /// </summary>
        internal static string action_id_generateqrcode {
            get {
                return ResourceManager.GetString("action_id_generateqrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string action_id_hide {
            get {
                return ResourceManager.GetString("action_id_hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string action_id_import {
            get {
                return ResourceManager.GetString("action_id_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string action_id_login {
            get {
                return ResourceManager.GetString("action_id_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string action_id_logout {
            get {
                return ResourceManager.GetString("action_id_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string action_id_move {
            get {
                return ResourceManager.GetString("action_id_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string action_id_paste {
            get {
                return ResourceManager.GetString("action_id_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string action_id_properties {
            get {
                return ResourceManager.GetString("action_id_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        internal static string action_id_recover {
            get {
                return ResourceManager.GetString("action_id_recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string action_id_save {
            get {
                return ResourceManager.GetString("action_id_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string action_id_scan {
            get {
                return ResourceManager.GetString("action_id_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string action_id_search {
            get {
                return ResourceManager.GetString("action_id_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string action_id_sendemail {
            get {
                return ResourceManager.GetString("action_id_sendemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string action_id_share {
            get {
                return ResourceManager.GetString("action_id_share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string action_id_show {
            get {
                return ResourceManager.GetString("action_id_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string action_id_switchusers {
            get {
                return ResourceManager.GetString("action_id_switchusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string action_id_update {
            get {
                return ResourceManager.GetString("action_id_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset template.
        /// </summary>
        internal static string action_id_update_template {
            get {
                return ResourceManager.GetString("action_id_update_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string alert_id_no {
            get {
                return ResourceManager.GetString("alert_id_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string alert_id_ok {
            get {
                return ResourceManager.GetString("alert_id_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm to delete.
        /// </summary>
        internal static string alert_id_remove {
            get {
                return ResourceManager.GetString("alert_id_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string alert_id_yes {
            get {
                return ResourceManager.GetString("alert_id_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassXYZ.Vault.
        /// </summary>
        internal static string Appname {
            get {
                return ResourceManager.GetString("Appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Date.
        /// </summary>
        internal static string database_modified_date {
            get {
                return ResourceManager.GetString("database_modified_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Time.
        /// </summary>
        internal static string database_modified_time {
            get {
                return ResourceManager.GetString("database_modified_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string database_name {
            get {
                return ResourceManager.GetString("database_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Railway Ticket 12306.
        /// </summary>
        internal static string entry_id_12306 {
            get {
                return ResourceManager.GetString("entry_id_12306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Agricultural Bank of China.
        /// </summary>
        internal static string entry_id_abc {
            get {
                return ResourceManager.GetString("entry_id_abc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Agricultural Bank of China - Credit Card.
        /// </summary>
        internal static string entry_id_abc_cc {
            get {
                return ResourceManager.GetString("entry_id_abc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alipay.
        /// </summary>
        internal static string entry_id_alipay {
            get {
                return ResourceManager.GetString("entry_id_alipay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon.
        /// </summary>
        internal static string entry_id_amazon {
            get {
                return ResourceManager.GetString("entry_id_amazon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple ID.
        /// </summary>
        internal static string entry_id_apple {
            get {
                return ResourceManager.GetString("entry_id_apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baidu.
        /// </summary>
        internal static string entry_id_baidu {
            get {
                return ResourceManager.GetString("entry_id_baidu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        internal static string entry_id_bank_account {
            get {
                return ResourceManager.GetString("entry_id_bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank of China.
        /// </summary>
        internal static string entry_id_boc {
            get {
                return ResourceManager.GetString("entry_id_boc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank of China - Credit Card.
        /// </summary>
        internal static string entry_id_boc_cc {
            get {
                return ResourceManager.GetString("entry_id_boc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string entry_id_box {
            get {
                return ResourceManager.GetString("entry_id_box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Mobile.
        /// </summary>
        internal static string entry_id_c_mobile {
            get {
                return ResourceManager.GetString("entry_id_c_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Telecom.
        /// </summary>
        internal static string entry_id_c_telecom {
            get {
                return ResourceManager.GetString("entry_id_c_telecom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Unicom.
        /// </summary>
        internal static string entry_id_c_unicom {
            get {
                return ResourceManager.GetString("entry_id_c_unicom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Construction Bank.
        /// </summary>
        internal static string entry_id_ccb {
            get {
                return ResourceManager.GetString("entry_id_ccb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Construction Bank - Credit Card.
        /// </summary>
        internal static string entry_id_ccb_cc {
            get {
                return ResourceManager.GetString("entry_id_ccb_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate of Marriage.
        /// </summary>
        internal static string entry_id_cert_of_marriage {
            get {
                return ResourceManager.GetString("entry_id_cert_of_marriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学信网.
        /// </summary>
        internal static string entry_id_chsi {
            get {
                return ResourceManager.GetString("entry_id_chsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Merchants Bank.
        /// </summary>
        internal static string entry_id_cmb {
            get {
                return ResourceManager.GetString("entry_id_cmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China Merchants Bank - Credit Card.
        /// </summary>
        internal static string entry_id_cmb_cc {
            get {
                return ResourceManager.GetString("entry_id_cmb_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants Securities.
        /// </summary>
        internal static string entry_id_cms {
            get {
                return ResourceManager.GetString("entry_id_cms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string entry_id_credit_card {
            get {
                return ResourceManager.GetString("entry_id_credit_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securities registration and Clearing.
        /// </summary>
        internal static string entry_id_csdc {
            get {
                return ResourceManager.GetString("entry_id_csdc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security.
        /// </summary>
        internal static string entry_id_csi {
            get {
                return ResourceManager.GetString("entry_id_csi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 社会统一用户基础平台.
        /// </summary>
        internal static string entry_id_csi_sz {
            get {
                return ResourceManager.GetString("entry_id_csi_sz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBS.
        /// </summary>
        internal static string entry_id_dbs {
            get {
                return ResourceManager.GetString("entry_id_dbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBS Credit Card.
        /// </summary>
        internal static string entry_id_dbs_cc {
            get {
                return ResourceManager.GetString("entry_id_dbs_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBS Vickers.
        /// </summary>
        internal static string entry_id_dbs_vickers {
            get {
                return ResourceManager.GetString("entry_id_dbs_vickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DockerHub.
        /// </summary>
        internal static string entry_id_docker {
            get {
                return ResourceManager.GetString("entry_id_docker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving license.
        /// </summary>
        internal static string entry_id_driving_license {
            get {
                return ResourceManager.GetString("entry_id_driving_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropbox.
        /// </summary>
        internal static string entry_id_dropbox {
            get {
                return ResourceManager.GetString("entry_id_dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evernote.
        /// </summary>
        internal static string entry_id_evernote {
            get {
                return ResourceManager.GetString("entry_id_evernote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string entry_id_facebook {
            get {
                return ResourceManager.GetString("entry_id_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        internal static string entry_id_github {
            get {
                return ResourceManager.GetString("entry_id_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string entry_id_google {
            get {
                return ResourceManager.GetString("entry_id_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 港澳通行证.
        /// </summary>
        internal static string entry_id_hk_txz {
            get {
                return ResourceManager.GetString("entry_id_hk_txz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei.
        /// </summary>
        internal static string entry_id_huawei {
            get {
                return ResourceManager.GetString("entry_id_huawei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial and Commercial Bank of China.
        /// </summary>
        internal static string entry_id_icbc {
            get {
                return ResourceManager.GetString("entry_id_icbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial and Commercial Bank of China - Credit Card.
        /// </summary>
        internal static string entry_id_icbc_cc {
            get {
                return ResourceManager.GetString("entry_id_icbc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        internal static string entry_id_idcard {
            get {
                return ResourceManager.GetString("entry_id_idcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JD.com.
        /// </summary>
        internal static string entry_id_jingdong {
            get {
                return ResourceManager.GetString("entry_id_jingdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lim &amp; Tan.
        /// </summary>
        internal static string entry_id_limtan {
            get {
                return ResourceManager.GetString("entry_id_limtan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        internal static string entry_id_linkedin {
            get {
                return ResourceManager.GetString("entry_id_linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        internal static string entry_id_microsoft {
            get {
                return ResourceManager.GetString("entry_id_microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netease.
        /// </summary>
        internal static string entry_id_netease {
            get {
                return ResourceManager.GetString("entry_id_netease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet.
        /// </summary>
        internal static string entry_id_nuget {
            get {
                return ResourceManager.GetString("entry_id_nuget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 坚果云.
        /// </summary>
        internal static string entry_id_nutstore {
            get {
                return ResourceManager.GetString("entry_id_nutstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCBC.
        /// </summary>
        internal static string entry_id_ocbc {
            get {
                return ResourceManager.GetString("entry_id_ocbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCBC Credit Card.
        /// </summary>
        internal static string entry_id_ocbc_cc {
            get {
                return ResourceManager.GetString("entry_id_ocbc_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneKey.
        /// </summary>
        internal static string entry_id_onekey {
            get {
                return ResourceManager.GetString("entry_id_onekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string entry_id_passport {
            get {
                return ResourceManager.GetString("entry_id_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use PassXYZ ?.
        /// </summary>
        internal static string entry_id_passxyz_usage {
            get {
                return ResourceManager.GetString("entry_id_passxyz_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string entry_id_paypal {
            get {
                return ResourceManager.GetString("entry_id_paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PICC人保.
        /// </summary>
        internal static string entry_id_picc {
            get {
                return ResourceManager.GetString("entry_id_picc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping An Bank.
        /// </summary>
        internal static string entry_id_pingan {
            get {
                return ResourceManager.GetString("entry_id_pingan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping An Bank - Credit Card.
        /// </summary>
        internal static string entry_id_pingan_cc {
            get {
                return ResourceManager.GetString("entry_id_pingan_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQ.
        /// </summary>
        internal static string entry_id_qq {
            get {
                return ResourceManager.GetString("entry_id_qq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDP.
        /// </summary>
        internal static string entry_id_sgx {
            get {
                return ResourceManager.GetString("entry_id_sgx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingPass.
        /// </summary>
        internal static string entry_id_singpass {
            get {
                return ResourceManager.GetString("entry_id_singpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        internal static string entry_id_skype {
            get {
                return ResourceManager.GetString("entry_id_skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP Services.
        /// </summary>
        internal static string entry_id_spgroup {
            get {
                return ResourceManager.GetString("entry_id_spgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申万宏源.
        /// </summary>
        internal static string entry_id_sywg {
            get {
                return ResourceManager.GetString("entry_id_sywg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳住房公积金.
        /// </summary>
        internal static string entry_id_sz_hpf {
            get {
                return ResourceManager.GetString("entry_id_sz_hpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳市地方税务局.
        /// </summary>
        internal static string entry_id_szlt {
            get {
                return ResourceManager.GetString("entry_id_szlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳燃气.
        /// </summary>
        internal static string entry_id_szrq {
            get {
                return ResourceManager.GetString("entry_id_szrq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taobao.
        /// </summary>
        internal static string entry_id_taobao {
            get {
                return ResourceManager.GetString("entry_id_taobao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        internal static string entry_id_twitter {
            get {
                return ResourceManager.GetString("entry_id_twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOB.
        /// </summary>
        internal static string entry_id_uob {
            get {
                return ResourceManager.GetString("entry_id_uob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOB Credit Card.
        /// </summary>
        internal static string entry_id_uob_cc {
            get {
                return ResourceManager.GetString("entry_id_uob_cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle license.
        /// </summary>
        internal static string entry_id_vehicle_license {
            get {
                return ResourceManager.GetString("entry_id_vehicle_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeChat.
        /// </summary>
        internal static string entry_id_wechat {
            get {
                return ResourceManager.GetString("entry_id_wechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 微博.
        /// </summary>
        internal static string entry_id_weibo {
            get {
                return ResourceManager.GetString("entry_id_weibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiaomi.
        /// </summary>
        internal static string entry_id_xiaomi {
            get {
                return ResourceManager.GetString("entry_id_xiaomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo.
        /// </summary>
        internal static string entry_id_yahoo {
            get {
                return ResourceManager.GetString("entry_id_yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宜停车.
        /// </summary>
        internal static string entry_id_ytc {
            get {
                return ResourceManager.GetString("entry_id_ytc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration is not correct..
        /// </summary>
        internal static string error_message_config1 {
            get {
                return ResourceManager.GetString("error_message_config1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the correct configuration..
        /// </summary>
        internal static string error_message_config2 {
            get {
                return ResourceManager.GetString("error_message_config2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format..
        /// </summary>
        internal static string error_message_invalid_url {
            get {
                return ResourceManager.GetString("error_message_invalid_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept privacy notice to use this app..
        /// </summary>
        internal static string error_message_privacy_notice {
            get {
                return ResourceManager.GetString("error_message_privacy_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a user first..
        /// </summary>
        internal static string export_error1 {
            get {
                return ResourceManager.GetString("export_error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支付宝生活号.
        /// </summary>
        internal static string field_id_alipay {
            get {
                return ResourceManager.GetString("field_id_alipay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All In One Net Password.
        /// </summary>
        internal static string field_id_all_in_one_net_p {
            get {
                return ResourceManager.GetString("field_id_all_in_one_net_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM PIN.
        /// </summary>
        internal static string field_id_atm_pin {
            get {
                return ResourceManager.GetString("field_id_atm_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Data.
        /// </summary>
        internal static string field_id_backup_data {
            get {
                return ResourceManager.GetString("field_id_backup_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string field_id_camera {
            get {
                return ResourceManager.GetString("field_id_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV.
        /// </summary>
        internal static string field_id_cvv {
            get {
                return ResourceManager.GetString("field_id_cvv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string field_id_email {
            get {
                return ResourceManager.GetString("field_id_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string field_id_file {
            get {
                return ResourceManager.GetString("field_id_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string field_id_gallery {
            get {
                return ResourceManager.GetString("field_id_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname, such as sftp.passxyz.com.
        /// </summary>
        internal static string field_id_hostname {
            get {
                return ResourceManager.GetString("field_id_hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotline.
        /// </summary>
        internal static string field_id_hotline {
            get {
                return ResourceManager.GetString("field_id_hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Banking Password.
        /// </summary>
        internal static string field_id_internet_banking_p {
            get {
                return ResourceManager.GetString("field_id_internet_banking_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Banking Username.
        /// </summary>
        internal static string field_id_internet_banking_u {
            get {
                return ResourceManager.GetString("field_id_internet_banking_u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Data.
        /// </summary>
        internal static string field_id_local_data {
            get {
                return ResourceManager.GetString("field_id_local_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string field_id_mobile {
            get {
                return ResourceManager.GetString("field_id_mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string field_id_name {
            get {
                return ResourceManager.GetString("field_id_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string field_id_notes {
            get {
                return ResourceManager.GetString("field_id_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string field_id_password {
            get {
                return ResourceManager.GetString("field_id_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Password.
        /// </summary>
        internal static string field_id_payment_password {
            get {
                return ResourceManager.GetString("field_id_payment_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Banking PIN.
        /// </summary>
        internal static string field_id_phone_banking_pin {
            get {
                return ResourceManager.GetString("field_id_phone_banking_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string field_id_pin {
            get {
                return ResourceManager.GetString("field_id_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string field_id_port {
            get {
                return ResourceManager.GetString("field_id_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query PIN.
        /// </summary>
        internal static string field_id_query_pin {
            get {
                return ResourceManager.GetString("field_id_query_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Data.
        /// </summary>
        internal static string field_id_remote_data {
            get {
                return ResourceManager.GetString("field_id_remote_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote folder, such as /home/tester/pxvault/.
        /// </summary>
        internal static string field_id_remote_folder {
            get {
                return ResourceManager.GetString("field_id_remote_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Password.
        /// </summary>
        internal static string field_id_service_password {
            get {
                return ResourceManager.GetString("field_id_service_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string field_id_template {
            get {
                return ResourceManager.GetString("field_id_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string field_id_title {
            get {
                return ResourceManager.GetString("field_id_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Password.
        /// </summary>
        internal static string field_id_trading_pin {
            get {
                return ResourceManager.GetString("field_id_trading_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U Key PIN.
        /// </summary>
        internal static string field_id_u_key_pin {
            get {
                return ResourceManager.GetString("field_id_u_key_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string field_id_url {
            get {
                return ResourceManager.GetString("field_id_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string field_id_username {
            get {
                return ResourceManager.GetString("field_id_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeChat Official Account.
        /// </summary>
        internal static string field_id_wechat {
            get {
                return ResourceManager.GetString("field_id_wechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected field.
        /// </summary>
        internal static string field_name_switch_label_isProtected {
            get {
                return ResourceManager.GetString("field_name_switch_label_isProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassXYZ.Resx.passxyz_en-us.t4xyz.
        /// </summary>
        internal static string file_name_template {
            get {
                return ResourceManager.GetString("file_name_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use fingerprint to login.
        /// </summary>
        internal static string fingerprint_login_message {
            get {
                return ResourceManager.GetString("fingerprint_login_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string group_id_bank {
            get {
                return ResourceManager.GetString("group_id_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string group_id_document {
            get {
                return ResourceManager.GetString("group_id_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Services.
        /// </summary>
        internal static string group_id_primary_services {
            get {
                return ResourceManager.GetString("group_id_primary_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin.
        /// </summary>
        internal static string group_id_recyclebin {
            get {
                return ResourceManager.GetString("group_id_recyclebin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string group_id_search {
            get {
                return ResourceManager.GetString("group_id_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file.
        /// </summary>
        internal static string import_data_file {
            get {
                return ResourceManager.GetString("import_data_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file (with key file).
        /// </summary>
        internal static string import_data_file_ex {
            get {
                return ResourceManager.GetString("import_data_file_ex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import this file!.
        /// </summary>
        internal static string import_error_msg {
            get {
                return ResourceManager.GetString("import_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot import this file! This user alreay exists..
        /// </summary>
        internal static string import_error_user_exits {
            get {
                return ResourceManager.GetString("import_error_user_exits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import key file.
        /// </summary>
        internal static string import_keyfile {
            get {
                return ResourceManager.GetString("import_keyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan key file QR code.
        /// </summary>
        internal static string import_keyfile_scan {
            get {
                return ResourceManager.GetString("import_keyfile_scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a KeePass or PassXYZ data file.
        /// </summary>
        internal static string import_message1 {
            get {
                return ResourceManager.GetString("import_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Storage Type.
        /// </summary>
        internal static string item_prop_cloud_type {
            get {
                return ResourceManager.GetString("item_prop_cloud_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Name.
        /// </summary>
        internal static string item_prop_icon_name {
            get {
                return ResourceManager.GetString("item_prop_icon_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        internal static string item_subtype_entry {
            get {
                return ResourceManager.GetString("item_subtype_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string item_subtype_group {
            get {
                return ResourceManager.GetString("item_subtype_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string item_subtype_notes {
            get {
                return ResourceManager.GetString("item_subtype_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PxEntry.
        /// </summary>
        internal static string item_subtype_pxentry {
            get {
                return ResourceManager.GetString("item_subtype_pxentry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string item_subtype_template {
            get {
                return ResourceManager.GetString("item_subtype_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using templates.
        /// </summary>
        internal static string item_subtype_using_template {
            get {
                return ResourceManager.GetString("item_subtype_using_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string label_id_attachment {
            get {
                return ResourceManager.GetString("label_id_attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom icon.
        /// </summary>
        internal static string label_id_custom_icon {
            get {
                return ResourceManager.GetString("label_id_custom_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password to login to PassXYZ..
        /// </summary>
        internal static string LoginPageWelcomeMessage {
            get {
                return ResourceManager.GetString("LoginPageWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Recovery.
        /// </summary>
        internal static string menu_id_data_recovery {
            get {
                return ResourceManager.GetString("menu_id_data_recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string menu_id_help {
            get {
                return ResourceManager.GetString("menu_id_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string menu_id_settings {
            get {
                return ResourceManager.GetString("menu_id_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string menu_id_template {
            get {
                return ResourceManager.GetString("menu_id_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string menu_id_user {
            get {
                return ResourceManager.GetString("menu_id_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string menu_id_users {
            get {
                return ResourceManager.GetString("menu_id_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot logout now, .
        /// </summary>
        internal static string message_id_alert_logout_disable {
            get {
                return ResourceManager.GetString("message_id_alert_logout_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the current user.
        /// </summary>
        internal static string message_id_alert_removing_current_user {
            get {
                return ResourceManager.GetString("message_id_alert_removing_current_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is a system group. System groups cannot be removed!.
        /// </summary>
        internal static string message_id_alert_removing_system_group {
            get {
                return ResourceManager.GetString("message_id_alert_removing_system_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string message_id_alert_saving {
            get {
                return ResourceManager.GetString("message_id_alert_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add attachments from.
        /// </summary>
        internal static string message_id_attachment_options {
            get {
                return ResourceManager.GetString("message_id_attachment_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in cloud storage configuration..
        /// </summary>
        internal static string message_id_cloud_config {
            get {
                return ResourceManager.GetString("message_id_cloud_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot edit binary.
        /// </summary>
        internal static string message_id_edit_binary {
            get {
                return ResourceManager.GetString("message_id_edit_binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save this icon. Icon size should be larger than 96 pixels..
        /// </summary>
        internal static string message_id_icon_size {
            get {
                return ResourceManager.GetString("message_id_icon_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user will be logout after the import. Please confirm to import.
        /// </summary>
        internal static string message_id_import_confirmation {
            get {
                return ResourceManager.GetString("message_id_import_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new database with Device Lock enabled will be created. Please assign a username for the new database..
        /// </summary>
        internal static string message_id_import_device_lock_desc {
            get {
                return ResourceManager.GetString("message_id_import_device_lock_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import .
        /// </summary>
        internal static string message_id_import_failure {
            get {
                return ResourceManager.GetString("message_id_import_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login first before import a.
        /// </summary>
        internal static string message_id_import_login_request {
            get {
                return ResourceManager.GetString("message_id_import_login_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP secret cannot be imported..
        /// </summary>
        internal static string message_id_import_otp_failure {
            get {
                return ResourceManager.GetString("message_id_import_otp_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the existing OTP secret?.
        /// </summary>
        internal static string message_id_import_otp_overwrite {
            get {
                return ResourceManager.GetString("message_id_import_otp_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP secret is saved.
        /// </summary>
        internal static string message_id_import_otp_saved {
            get {
                return ResourceManager.GetString("message_id_import_otp_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After import, please login using the original master password. Please create a user name for the data file:.
        /// </summary>
        internal static string message_id_importData {
            get {
                return ResourceManager.GetString("message_id_importData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully imported data file.
        /// </summary>
        internal static string message_id_importDataSuccess {
            get {
                return ResourceManager.GetString("message_id_importDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data file can be recovered from backup file. If cannot work, please try to recover from cloud file.
        ///
        ///- **Local Data** can be recovered from remote data or backup data
        ///- **Remote Data** can be recovered using local data.
        /// </summary>
        internal static string message_id_recover_datafile {
            get {
                return ResourceManager.GetString("message_id_recover_datafile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot synchronize file.
        /// </summary>
        internal static string message_id_sync_failure {
            get {
                return ResourceManager.GetString("message_id_sync_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization completed.
        /// </summary>
        internal static string message_id_sync_success {
            get {
                return ResourceManager.GetString("message_id_sync_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template has been updated..
        /// </summary>
        internal static string message_id_update_template {
            get {
                return ResourceManager.GetString("message_id_update_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter field name here.
        /// </summary>
        internal static string ph_id_key {
            get {
                return ResourceManager.GetString("ph_id_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        internal static string ph_id_password {
            get {
                return ResourceManager.GetString("ph_id_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your title.
        /// </summary>
        internal static string ph_id_title {
            get {
                return ResourceManager.GetString("ph_id_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter field value here.
        /// </summary>
        internal static string ph_id_value {
            get {
                return ResourceManager.GetString("ph_id_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Privacy Notice
        ///
        ///
        ///This privacy notice discloses the privacy practices for PassXYZ application and our websites:
        ///- PassXYZ, PassXYZ Cloud and PassXYZ.Vault
        ///- https://passxyz.github.io
        ///- https://github.com/passxyz
        ///
        ///## Information Collection, Use, and Sharing 
        ///
        ///This website is built using the services provided by GitHub. It is a static website and does not collect any information. Please refer to the GitHub Privacy Statement about the agreement before you use GitHub services.
        ///
        ///PassXYZ application  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string privacy_notice {
            get {
                return ResourceManager.GetString("privacy_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose an item to be created: .
        /// </summary>
        internal static string pt_id_choosetemplate {
            get {
                return ResourceManager.GetString("pt_id_choosetemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a user to switch.
        /// </summary>
        internal static string pt_id_switchusers {
            get {
                return ResourceManager.GetString("pt_id_switchusers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting users.
        /// </summary>
        internal static string settings_deleting_users {
            get {
                return ResourceManager.GetString("settings_deleting_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to use an empty master password..
        /// </summary>
        internal static string settings_empty_password {
            get {
                return ResourceManager.GetString("settings_empty_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export database to other devices or cloud storage.
        /// </summary>
        internal static string settings_export_remark {
            get {
                return ResourceManager.GetString("settings_export_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export database.
        /// </summary>
        internal static string settings_export_title {
            get {
                return ResourceManager.GetString("settings_export_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint is not supported.
        /// </summary>
        internal static string settings_fingerprint_disabled {
            get {
                return ResourceManager.GetString("settings_fingerprint_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable fingerprint to unlock.
        /// </summary>
        internal static string settings_fingerprint_remark {
            get {
                return ResourceManager.GetString("settings_fingerprint_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint setup.
        /// </summary>
        internal static string settings_fingerprint_title {
            get {
                return ResourceManager.GetString("settings_fingerprint_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Settings.
        /// </summary>
        internal static string settings_keyFileField_Key {
            get {
                return ResourceManager.GetString("settings_keyFileField_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Lock enabled. Device Lock Key can be exported.
        /// </summary>
        internal static string settings_keyFileField_Value1 {
            get {
                return ResourceManager.GetString("settings_keyFileField_Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Lock disabled.
        /// </summary>
        internal static string settings_keyFileField_Value2 {
            get {
                return ResourceManager.GetString("settings_keyFileField_Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Lock.
        /// </summary>
        internal static string settings_keyFileField_Value3 {
            get {
                return ResourceManager.GetString("settings_keyFileField_Value3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password, name etc..
        /// </summary>
        internal static string settings_manage_db_remark {
            get {
                return ResourceManager.GetString("settings_manage_db_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage database.
        /// </summary>
        internal static string settings_manage_db_title {
            get {
                return ResourceManager.GetString("settings_manage_db_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or delete users.
        /// </summary>
        internal static string settings_manage_users_remark {
            get {
                return ResourceManager.GetString("settings_manage_users_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your master password.
        /// </summary>
        internal static string settings_manage_users_reset_password {
            get {
                return ResourceManager.GetString("settings_manage_users_reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        internal static string settings_manage_users_title {
            get {
                return ResourceManager.GetString("settings_manage_users_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a suitable merge method.
        /// </summary>
        internal static string settings_merge_method_remark {
            get {
                return ResourceManager.GetString("settings_merge_method_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge method: .
        /// </summary>
        internal static string settings_merge_method_title {
            get {
                return ResourceManager.GetString("settings_merge_method_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to synchronize using OneDrive.
        /// </summary>
        internal static string settings_onedrive_remark {
            get {
                return ResourceManager.GetString("settings_onedrive_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneDrive Username is.
        /// </summary>
        internal static string settings_onedrive_status {
            get {
                return ResourceManager.GetString("settings_onedrive_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using OneDrive sync current database.
        /// </summary>
        internal static string settings_onedrive_title {
            get {
                return ResourceManager.GetString("settings_onedrive_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Lock Key.
        /// </summary>
        internal static string settings_security_DeviceLockKey {
            get {
                return ResourceManager.GetString("settings_security_DeviceLockKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Device Lock Key.
        /// </summary>
        internal static string settings_security_DLK_Created_failure {
            get {
                return ResourceManager.GetString("settings_security_DLK_Created_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Lock Key is created successfully.
        /// </summary>
        internal static string settings_security_DLK_Created_success {
            get {
                return ResourceManager.GetString("settings_security_DLK_Created_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a Device Lock Key to login as user .
        /// </summary>
        internal static string settings_security_DLK_message1 {
            get {
                return ResourceManager.GetString("settings_security_DLK_message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This QR code is not a PassXYZ Device Lock Key.
        /// </summary>
        internal static string settings_security_DLK_Wrong_Format {
            get {
                return ResourceManager.GetString("settings_security_DLK_Wrong_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Device Lock Key. It is for user.
        /// </summary>
        internal static string settings_security_DLK_Wrong_User {
            get {
                return ResourceManager.GetString("settings_security_DLK_Wrong_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Lock Key QR code.
        /// </summary>
        internal static string settings_security_generate_QRCode {
            get {
                return ResourceManager.GetString("settings_security_generate_QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string settings_security_permission {
            get {
                return ResourceManager.GetString("settings_security_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permission is required to use this app.
        /// </summary>
        internal static string settings_security_permission_desc {
            get {
                return ResourceManager.GetString("settings_security_permission_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe Later.
        /// </summary>
        internal static string settings_security_permission_negative {
            get {
                return ResourceManager.GetString("settings_security_permission_negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned QR code.
        /// </summary>
        internal static string settings_security_scan_result {
            get {
                return ResourceManager.GetString("settings_security_scan_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Device Lock Key to a file.
        /// </summary>
        internal static string settings_security_share_keyfile {
            get {
                return ResourceManager.GetString("settings_security_share_keyfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Device Lock.
        /// </summary>
        internal static string settings_security_UsingDeviceLock {
            get {
                return ResourceManager.GetString("settings_security_UsingDeviceLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sychornize with other devices through messaging app.
        /// </summary>
        internal static string settings_sync_remark {
            get {
                return ResourceManager.GetString("settings_sync_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sychronize database.
        /// </summary>
        internal static string settings_sync_title {
            get {
                return ResourceManager.GetString("settings_sync_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, import or delete.
        /// </summary>
        internal static string settings_template_remark {
            get {
                return ResourceManager.GetString("settings_template_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage template.
        /// </summary>
        internal static string settings_template_title {
            get {
                return ResourceManager.GetString("settings_template_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time before locking database when the application is inactive.
        /// </summary>
        internal static string settings_timer_remark {
            get {
                return ResourceManager.GetString("settings_timer_remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer setup.
        /// </summary>
        internal static string settings_timer_title {
            get {
                return ResourceManager.GetString("settings_timer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string settings_timer_unit_hour {
            get {
                return ResourceManager.GetString("settings_timer_unit_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string settings_timer_unit_minutes {
            get {
                return ResourceManager.GetString("settings_timer_unit_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string settings_timer_unit_seconds {
            get {
                return ResourceManager.GetString("settings_timer_unit_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated password successfully..
        /// </summary>
        internal static string settings_updated_password {
            get {
                return ResourceManager.GetString("settings_updated_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating password ....
        /// </summary>
        internal static string settings_updating_password {
            get {
                return ResourceManager.GetString("settings_updating_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up failed, please check the format of username and password.
        /// </summary>
        internal static string SignUpErrorMessage {
            get {
                return ResourceManager.GetString("SignUpErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user already exists. You can try to login with this username..
        /// </summary>
        internal static string SignUpErrorMessage1 {
            get {
                return ResourceManager.GetString("SignUpErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password and Password confirmation do not exactly match..
        /// </summary>
        internal static string SignUpErrorMessage2 {
            get {
                return ResourceManager.GetString("SignUpErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new database or import a KeePass database..
        /// </summary>
        internal static string SignUpPageMessage {
            get {
                return ResourceManager.GetString("SignUpPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpPageTitle {
            get {
                return ResourceManager.GetString("SignUpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created a new user.
        /// </summary>
        internal static string SiguUpMessage {
            get {
                return ResourceManager.GetString("SiguUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud storage configuration.
        /// </summary>
        internal static string title_cloud_config {
            get {
                return ResourceManager.GetString("title_cloud_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File on cloud drive.
        /// </summary>
        internal static string user_id_cloud {
            get {
                return ResourceManager.GetString("user_id_cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization is disabled.
        /// </summary>
        internal static string user_id_disabled {
            get {
                return ResourceManager.GetString("user_id_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file.
        /// </summary>
        internal static string user_id_local {
            get {
                return ResourceManager.GetString("user_id_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronized with cloud.
        /// </summary>
        internal static string user_id_synced {
            get {
                return ResourceManager.GetString("user_id_synced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing with cloud ....
        /// </summary>
        internal static string user_id_syncing {
            get {
                return ResourceManager.GetString("user_id_syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
